# M2177.003100 Deep Learning Assignment 0<br> Part 3. PyTorch Tutorial

Adapted by Hyungi Kim from the IPython version of the PyTorch tutorial (https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) by Soumith Chintala.

In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

## Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6227, 0.7485, 0.0936],
        [0.0684, 0.6319, 0.8437],
        [0.5350, 0.8033, 0.6329],
        [0.5450, 0.4069, 0.7676],
        [0.6925, 0.5619, 0.5040]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4104,  0.6019, -0.8488],
        [-0.5575, -0.8112,  0.1152],
        [ 0.2400,  0.9690,  0.2135],
        [ 0.8586, -1.5513,  0.0685],
        [ 0.5038, -0.0890, -0.8694]])


Get its size:



In [7]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

## Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.5749,  0.6358, -0.0659],
        [-0.5514, -0.6088,  0.5244],
        [ 0.2670,  1.7774,  0.9340],
        [ 1.5255, -0.9452,  0.4598],
        [ 0.6111,  0.0794, -0.6466]])


Addition: syntax 2



In [9]:
print(torch.add(x, y))

tensor([[ 0.5749,  0.6358, -0.0659],
        [-0.5514, -0.6088,  0.5244],
        [ 0.2670,  1.7774,  0.9340],
        [ 1.5255, -0.9452,  0.4598],
        [ 0.6111,  0.0794, -0.6466]])


Addition: providing an output tensor as argument



In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5749,  0.6358, -0.0659],
        [-0.5514, -0.6088,  0.5244],
        [ 0.2670,  1.7774,  0.9340],
        [ 1.5255, -0.9452,  0.4598],
        [ 0.6111,  0.0794, -0.6466]])


Addition: in-place



In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.5749,  0.6358, -0.0659],
        [-0.5514, -0.6088,  0.5244],
        [ 0.2670,  1.7774,  0.9340],
        [ 1.5255, -0.9452,  0.4598],
        [ 0.6111,  0.0794, -0.6466]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [12]:
print(x[:, 1])

tensor([ 0.6019, -0.8112,  0.9690, -1.5513, -0.0890])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.0332])
2.0331547260284424


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

## Converting a Torch Tensor to a NumPy Array



In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


tensor([3.0332], device='cuda:0')
tensor([3.0332], dtype=torch.float64)



Autograd: Automatic Differentiation
===================================

Central to all neural networks in PyTorch is the ``autograd`` package.
Let’s first briefly visit this, and we will then go to training our
first neural network.


The ``autograd`` package provides automatic differentiation for all operations
on Tensors. It is a define-by-run framework, which means that your backprop is
defined by how your code is run, and that every single iteration can be
different.

Let us see this in more simple terms with some examples.

Tensor
--------

``torch.Tensor`` is the central class of the package. If you set its attribute
``.requires_grad`` as ``True``, it starts to track all operations on it. When
you finish your computation you can call ``.backward()`` and have all the
gradients computed automatically. The gradient for this tensor will be
accumulated into ``.grad`` attribute.

To stop a tensor from tracking history, you can call ``.detach()`` to detach
it from the computation history, and to prevent future computation from being
tracked.

To prevent tracking history (and using memory), you can also wrap the code block
in ``with torch.no_grad():``. This can be particularly helpful when evaluating a
model because the model may have trainable parameters with
``requires_grad=True``, but for which we don't need the gradients.

There’s one more class which is very important for autograd
implementation - a ``Function``.

``Tensor`` and ``Function`` are interconnected and build up an acyclic
graph, that encodes a complete history of computation. Each tensor has
a ``.grad_fn`` attribute that references a ``Function`` that has created
the ``Tensor`` (except for Tensors created by the user - their
``grad_fn is None``).

If you want to compute the derivatives, you can call ``.backward()`` on
a ``Tensor``. If ``Tensor`` is a scalar (i.e. it holds a one element
data), you don’t need to specify any arguments to ``backward()``,
however if it has more elements, you need to specify a ``gradient``
argument that is a tensor of matching shape.



Create a tensor and set ``requires_grad=True`` to track computation with it



In [20]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation:



In [21]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


``y`` was created as a result of an operation, so it has a ``grad_fn``.



In [22]:
print(y.grad_fn)

Do more operations on ``y``



In [23]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
flag in-place. The input flag defaults to ``False`` if not given.



In [24]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


Gradients
---------
Let's backprop now.
Because ``out`` contains a single scalar, ``out.backward()`` is
equivalent to ``out.backward(torch.tensor(1.))``.



In [25]:
out.backward()

Print gradients d(out)/dx




In [26]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.
We have that $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.



You can also stop autograd from tracking history on Tensors
with ``.requires_grad=True`` either by wrapping the code block in
``with torch.no_grad():``



In [27]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
	print((x ** 2).requires_grad)

True
True
False


Or by using ``.detach()`` to get a new Tensor with the same
content but that does not require gradients:



In [28]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


**Read Later:**

Document about ``autograd.Function`` is at
https://pytorch.org/docs/stable/autograd.html#function




Neural Networks
===============

Neural networks can be constructed using the ``torch.nn`` package.

Now that you had a glimpse of ``autograd``, ``nn`` depends on
``autograd`` to define models and differentiate them.
An ``nn.Module`` contains layers, and a method ``forward(input)``\ that
returns the ``output``.


A typical training procedure for a neural network is as follows:

- Define the neural network that has some learnable parameters (or
  weights)
- Iterate over a dataset of inputs
- Process input through the network
- Compute the loss (how far is the output from being correct)
- Propagate gradients back into the network’s parameters
- Update the weights of the network, typically using a simple update rule:
  ``weight = weight - learning_rate * gradient``

Define the network
------------------

Let’s define this network:



In [29]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # an affine operation: y = Wx + b
        self.linear = nn.Linear(100, 10)

    def forward(self, x):
        x = self.linear(x)
        return x


net = Net()
print(net)

Net(
  (linear): Linear(in_features=100, out_features=10, bias=True)
)


You just have to define the ``forward`` function, and the ``backward``
function (where gradients are computed) is automatically defined for you
using ``autograd``.
You can use any of the Tensor operations in the ``forward`` function.

The learnable parameters of a model are returned by ``net.parameters()``



In [30]:
params = list(net.parameters())
print(len(params))
print(params[0].size())
print(params[1].size())

2
torch.Size([10, 100])
torch.Size([10])


Let's try a random 1x100 input.
Note: expected input size of this net is 100.

In [31]:
input = torch.randn(1, 100)
out = net(input)
print(out)

tensor([[ 0.4732, -1.2420, -0.6449, -0.1784, -0.4528,  0.8447, -0.9540,  0.2553,
          0.2767, -0.2727]], grad_fn=<AddmmBackward>)


<div class="alert alert-info"><h4>Note</h4><p>``torch.nn`` only supports mini-batches. The entire ``torch.nn``
    package only supports inputs that are a mini-batch of samples, and not
    a single sample.

    For example, ``nn.Linear`` will take in a 2D Tensor of
    ``nSamples x input_size``.

    If you have a single sample, just use ``input.unsqueeze(0)`` to add
    a fake batch dimension.</p></div>

Before proceeding further, let's recap all the classes you’ve seen so far.

**Recap:**
  -  ``torch.Tensor`` - A *multi-dimensional array* with support for autograd
     operations like ``backward()``. Also *holds the gradient* w.r.t. the
     tensor.
  -  ``nn.Module`` - Neural network module. *Convenient way of
     encapsulating parameters*, with helpers for moving them to GPU,
     exporting, loading, etc.
  -  ``nn.Parameter`` - A kind of Tensor, that is *automatically
     registered as a parameter when assigned as an attribute to a*
     ``Module``.
  -  ``autograd.Function`` - Implements *forward and backward definitions
     of an autograd operation*. Every ``Tensor`` operation creates at
     least a single ``Function`` node that connects to functions that
     created a ``Tensor`` and *encodes its history*.

**At this point, we covered:**
  -  Defining a neural network
  -  Processing inputs

**Still Left:**
  -  Computing the loss and calling backward
  -  Updating the weights of the network

Loss Function
-------------
A loss function takes the (output, target) pair of inputs, and computes a
value that estimates how far away the output is from the target.

There are several different
`loss functions <https://pytorch.org/docs/nn.html#loss-functions>`_ under the
nn package .
A simple loss is: ``nn.MSELoss`` which computes the mean-squared error
between the input and the target.

For example:



In [32]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(2.1390, grad_fn=<MseLossBackward>)


when we call ``loss.backward()``, the whole graph is differentiated
w.r.t. the loss, and all Tensors in the graph that has ``requires_grad=True``
will have their ``.grad`` Tensor accumulated with the gradient.

For illustration, let us follow a few steps backward:



In [33]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear

Backprop
--------
To backpropagate the error all we have to do is to ``loss.backward()``.
You need to clear the existing gradients though, else gradients will be
accumulated to existing gradients.


Now we shall call ``loss.backward()``, and have a look at conv1's bias
gradients before and after the backward.



In [34]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('linear.bias.grad before backward')
print(net.linear.bias.grad)

loss.backward()

print('linear.bias.grad after backward')
print(net.linear.bias.grad)

linear.bias.grad before backward
None
linear.bias.grad after backward
tensor([ 1.4256e-01, -4.0304e-01, -3.4852e-01,  1.2336e-01,  1.0335e-01,
         3.3655e-01, -4.1348e-01,  7.1323e-02,  4.8594e-01,  1.7675e-04])


Now, we have seen how to use loss functions.

**Read Later:**

  The neural network package contains various modules and loss functions
  that form the building blocks of deep neural networks. A full list with
  documentation is `here <https://pytorch.org/docs/nn>`_.

**The only thing left to learn is:**

  - Updating the weights of the network

Update the weights
------------------
The simplest update rule used in practice is the Stochastic Gradient
Descent (SGD):

     ``weight = weight - learning_rate * gradient``

We can implement this using simple Python code:

.. code:: python

    learning_rate = 0.01
    for f in net.parameters():
        f.data.sub_(f.grad.data * learning_rate)

However, as you use neural networks, you want to use various different
update rules.
To enable this, we built a small package: ``torch.optim`` that
implements all these methods. Using it is very simple:



In [35]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update

.. Note::

      Observe how gradient buffers had to be manually set to zero using
      ``optimizer.zero_grad()``. This is because gradients are accumulated
      as explained in the `Backprop`_ section.




Training a Classifier
=====================

This is it. You have seen how to define neural networks, compute loss and make
updates to the weights of the network.

Now you might be thinking,

What about data?
----------------

Generally, when you have to deal with image, text, audio or video data,
you can use standard python packages that load data into a numpy array.
Then you can convert this array into a ``torch.*Tensor``.

-  For images, packages such as Pillow, OpenCV are useful
-  For audio, packages such as scipy and librosa
-  For text, either raw Python or Cython based loading, or NLTK and
   SpaCy are useful

Specifically for vision, we have created a package called
``torchvision``, that has data loaders for common datasets such as
Imagenet, CIFAR10, MNIST, etc. and data transformers for images, viz.,
``torchvision.datasets`` and ``torch.utils.data.DataLoader``.

This provides a huge convenience and avoids writing boilerplate code.

For this tutorial, we will use the MNIST dataset.
It is a dataset of handwritten digits which is widely used in the field of machine learning.
It has the classes '0' to '9'.
The images in MNIST are of size 1x28x28, i.e. 1-channel images of 28x28 pixels in size.


Training an image classifier
----------------------------

We will do the following steps in order:

1. Load and normalizing the MNIST training and test datasets using
   ``torchvision``
2. Define a network
3. Define a loss function
4. Train the network on the training data
5. Test the network on the test data

## 1. Loading and normalizing MNIST

Using ``torchvision``, it’s extremely easy to load MNIST.



In [36]:
from __future__ import print_function
import torch
from torchvision import datasets, transforms

The output of torchvision datasets are PILImage images of range [0, 1].
We transform them to Tensors of normalized range [-1, 1].
<div class="alert alert-info"><h4>Note</h4><p>If running on Windows and you get a BrokenPipeError, try setting
    the num_worker of torch.utils.data.DataLoader() to 0.</p></div>



In [37]:
transform=transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
    ])

trainset = datasets.MNIST('./data', train=True, download=True,
                   transform=transform)
testset = datasets.MNIST('./data', train=False,
                   transform=transform)

Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw


Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw
Processing...



Done!


/home/ccw/anaconda3/envs/deep-learning-20/lib/python3.8/site-packages/torchvision/datasets/mnist.py:469: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629395347/work/torch/csrc/utils/tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [106]:
# Training settings
batch_size = 64
test_batch_size = 1000
no_cuda = False
seed = 1
input_size = 28*28 # 784
num_classes = 10

use_cuda = not no_cuda and torch.cuda.is_available()

torch.manual_seed(seed)

device = torch.device("cuda" if use_cuda else "cpu")

kwargs = {}
if use_cuda:
    kwargs.update({'num_workers': 1,
                   'pin_memory': True,
                   'shuffle': True},
                 )
    
train_loader = torch.utils.data.DataLoader(dataset=trainset, batch_size=batch_size, **kwargs)
test_loader = torch.utils.data.DataLoader(dataset=testset, batch_size=test_batch_size, **kwargs)

In [107]:
print(use_cuda)

True


## 2. Define a network

In this assignment, we will use logistic regression model

In [108]:
net = nn.Linear(input_size, num_classes)
    
net = net.to(device)
print(net)
print(list(net.parameters()))

Linear(in_features=784, out_features=10, bias=True)
[Parameter containing:
tensor([[ 0.0184, -0.0158, -0.0069,  ...,  0.0068, -0.0041,  0.0025],
        [-0.0274, -0.0224, -0.0309,  ..., -0.0029,  0.0013, -0.0167],
        [ 0.0282, -0.0095, -0.0340,  ..., -0.0141,  0.0056, -0.0335],
        ...,
        [-0.0355,  0.0131,  0.0193,  ..., -0.0324,  0.0316,  0.0120],
        [ 0.0178,  0.0196,  0.0114,  ...,  0.0253, -0.0041,  0.0252],
        [ 0.0303, -0.0011, -0.0183,  ...,  0.0069,  0.0037, -0.0249]],
       device='cuda:0', requires_grad=True), Parameter containing:
tensor([ 0.0306,  0.0015,  0.0277,  0.0178, -0.0313,  0.0318,  0.0006,  0.0085,
        -0.0246,  0.0139], device='cuda:0', requires_grad=True)]


## 3. Define a Loss function and optimizer
Let's use a cross entropy loss and SGD with momentum.


In [109]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

## 4. Train the network

This is when things start to get interesting.
We simply have to loop over our data iterator, and feed the inputs to the
network and optimize.



In [110]:
# training settings
epochs = 10
log_interval = 100
save_model = True

In [111]:
def train(model, device, train_loader, optimizer, criterion, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        # TODO: training code which optimizes model
        ##### YOUR CODE START #####
        optimizer.zero_grad()
        data = data.cuda()
        target = target.cuda()
        output = net(data.view(data.shape[0], -1))
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        
        ##### YOUR CODE END #####
        
        if batch_idx % log_interval == 0:
            print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)} ({(100. * batch_idx / len(train_loader)):.0f}%)]\tLoss: {loss.item():.6f}')

In [112]:
def test(model, device, test_loader, criterion):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            # TODO: test code which evaluates model
            ##### YOUR CODE START #####
            data = data.cuda()
            target = target.cuda()
            output = net(data.view(data.shape[0], -1))
            test_loss += criterion(output, target)
            output = torch.argmax(output, dim=1)
            correct += torch.sum(output==target).item()
            

            ##### YOUR CODE END #####


    test_loss /= len(test_loader.dataset)
    print(len(test_loader.dataset))
    print(f'\nTest set: Average loss: {test_loss:.4f}, Accuracy: {correct}/{len(test_loader.dataset)} ({(100. * correct / len(test_loader.dataset)):.0f}%)\n')

In [113]:
for epoch in range(1, epochs + 1):
    train(net, device, train_loader, optimizer, criterion, epoch)
    test(net, device, test_loader, criterion)

Train Epoch: 1 [0/60000 (0%)]	Loss: 2.229980
Train Epoch: 1 [6400/60000 (11%)]	Loss: 0.788289
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.798303
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.585324
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.516518
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.373188
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.434780
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.445312
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.480927
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.356047

10000

Test set: Average loss: 0.0004, Accuracy: 8923/10000 (89%)

Train Epoch: 2 [0/60000 (0%)]	Loss: 0.345222
Train Epoch: 2 [6400/60000 (11%)]	Loss: 0.464940
Train Epoch: 2 [12800/60000 (21%)]	Loss: 0.318640
Train Epoch: 2 [19200/60000 (32%)]	Loss: 0.591674
Train Epoch: 2 [25600/60000 (43%)]	Loss: 0.309283
Train Epoch: 2 [32000/60000 (53%)]	Loss: 0.305212
Train Epoch: 2 [38400/60000 (64%)]	Loss: 0.269131
Train Epoch: 2 [44800/60000 (75%)]	Loss: 0.338327
Train Epoch: 2 [51200/60000 (85%)]	Loss: 0.4

Let's quickly save our trained model:



In [114]:
if save_model:
    torch.save(net.state_dict(), "mnist_net.pt")